### ISSUE TITLE
Definir a versão do eagle usada no componente para documentação

### ISSUE THREAD

**Issue by Wanghley** [infocbra/PS25454-socket#1]
@HumbertoMesquita qual a versão do eagle que utilizou para criar o componente?

Talvez faça sentido criar um repositório só para ele e deixar acessível publicamente como open-source para a comunidade acadêmica. Faz sentido, prof @oliveirafhm?

**Comment by oliveirafhm** [comment]
@Wanghley 
Faz sentido sim. Deve-se incluir a referência ao projeto, fomento e as pessoas envolvidas.
Vincule no Trello os repositórios criados para o projeto.

**Comment by HumbertoMesquita** [comment]
@Wanghley a versão utilizado do eagle foi a  9.6.2
